### ISSUE TITLE
Build from source import error

### ISSUE THREAD

**Issue by wathen** [BoldingBruggeman/fabmos#7]
I have encountered this error 
```
import awex
ModuleNotFoundError: No module named 'awex'

```
after installing FABM-OS via the [build from source](https://github.com/BoldingBruggeman/fabmos/wiki#build-from-source) instructions.

I have made a little script from the build from source instructions bellow that installs FABMOS but creates this error when you import it
```
#!/bin/bash

git clone --recursive https://github.com/BoldingBruggeman/fabmos.git

cd fabmos

mamba env create -f environment.yml

mamba activate fabmos

python -m pip install .

python -c "import fabmos"
```

**Comment by jornbr** [comment]
That's caused by fabmos requiring the latest pygetm (which includes awex). Unfortunately that's not on Anaconda yet. The only workaround at present is to [install pygetm from source](https://github.com/BoldingBruggeman/getm-rewrite?tab=readme-ov-file#manual-build-and-install).  However, you'll want to install it into the "fabmos" environment, not the "pygetm" environment, with something like:

```
git clone --recursive https://github.com/BoldingBruggeman/getm-rewrite.git
cd getm-rewrite
conda activate fabmos
conda env update -f environment.yml
source ./install
```

**Comment by wathen** [comment]
Ok, thanks very much

**Comment by jornbr** [comment]
The fabmos and pygetm builds on conda-forge have now both been updated, so this should no longer cause trouble.
